version: '3'
services:
  postgres:
    image: postgres:12.4
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
